---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCfihLBovhbbLO1P5fapW7qv/r2GPYSwpRSH5rFFoVNkwC3iO8j5lhhdJ+NYJPTPd0aVUFKcL0U9Cfi9kl1zVNEN1Hyq/MU+VZHF2jBWrO8RVqrHcgnZF+AZV1p0BRHvcrq8POneGj96L5NGYfG6pBbk+Tl92TeGa4nEBW2X8D78dxFW7V46tEUy7upyH2Ez925RP4irUNVtA3DgmDr0sUJoYQ22/0ZvNUV7Dq713n37o01QpSR836182mU9baB/r7F86lNW/ku7WeMBQ7HUGvcbPitT2/BbVjWdYOH66iuPiS/xgOHXTVyAxKLXRR2s7HlNAlG4kAIwxj2A0Cmi4+OYfgJduvn1C1j5aizYegLSl8FO021PhTm/hYYDZRazWWjet+81uBmXJCv99mfVWVd9pKUUMvE/tx4EOYhu+RLCtUNmQ16pp5ctlq0QCsp8C7ad21PaPlp0Qb3OXGXzh3/n7xwUCkySFPXXRlT9B8Gj3F6lRZpFRce/8i4tOn//8WJQv+xx4ApArWBjwTuIpNzx8D+V9Bsue00CuuHaMSy6b3JO5Ai9xSBhKo/kVpIRffMjb3GPBdjovIUhXhBPaFFFRJNTCuW/5jkPZYVFIneMV4hUSlz+WaIvgZ+0WjkqBwet3S60oczqJZqw9hiwR2HSIfOiWYNaYAQWlFBRpKDrT05R2gGaqFgdUF5fhN2ElUCfLwLeXyZpQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
