---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vaultwarden-admin
  namespace: security
spec:
  encryptedData:
    admin-token: AgAjIHYpoc23WLTGo8AJvjthYqCbBHxrb+/qt+pfmdelKPn/DrcMCt10nOUqjn/p62Cd5uUwhEx9IPstbZExwBYHMxNyd5tly0a/Hr5rQGMsFurfUL7ZSPmmo/0TuHtQwftSKOc1BhVXCsI1BNvoKV0cqamap2mxFUzb3Z6N23DswJeBb6BexLBGQup/iNCih5YtGrlN8uXsKGdnkWyQSDuvylxrAL6ryqsCCeV9JrjFEFuMR0B37DLTQVae/HPiJgxSDTepTXh7l1Tv3ZDTYXd7Hm8gCcWfiyjjQpy3lA8kq2AfpAfTxfyvDzLfeKJTe9xgsgIbZFYZfAhUcB4Zh6D1wS4XnaVjKNLIsDtV3H0up5Moan27RQMqkAezEIGZpB08MCOk1NKR2GfKimiH45aN19uE1WXYq7JiOwBIhsnBLRfBkgcjaIXnoSEP0tfPZSsPnakCr4BAvGPnr8vOJgpDi8nLEXiyxS3SY+UYxWrsJcxVFm6btnqoB1g2WgIPzMipf8m0C/g6xlNf/Q4g19A1Y1tLg0TvgxNzEjOCmhbQhnxfUfW19ObHrXCh/CBJz3qc1wssq8QjG7aUqwCIac8WgKZ5R2VLKXWBCEwcPefZkMMQJtkU9lVAjAYQQDIpBp/tqWRTgX/96p3ULqqhhVHH1+0vjDpa06S+M9C+AW5N1o2xXUElnWhvU9NMchoH+cE6nT0ha4gJpQ==
  template:
    metadata:
      creationTimestamp: null
      name: vaultwarden-admin
      namespace: security
