apiVersion: v2
name: sealed-secrets
description: Sealed Secrets controller for encrypting secrets in git
version: 1.0.0
appVersion: "0.27.3"
type: application

dependencies:
  - name: sealed-secrets
    version: "2.17.1"
    repository: "https://bitnami-labs.github.io/sealed-secrets"
