apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pihole.fullname" . }}-custom-dns
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
data:
  05-custom.conf: |
    {{- if .Values.localDns.enabled }}
    # Homelab: route all *.home records to the k3s node IP.
    address=/{{ .Values.localDns.domainSuffix }}/{{ .Values.localDns.ip }}
    {{- end }}
