name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Ansible + Collections
        run: |
          pip install ansible ansible-lint
          ansible-galaxy collection install ansible.posix community.general

      - name: Run Ansible Lint
        run: ansible-lint ansible/roles

  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.1

      - name: Lint Helm Charts
        run: |
          # Lint all charts
          for chart in $(find apps -name Chart.yaml -print); do
            chart_dir=$(dirname "$chart")
            echo "=== Helm lint $chart_dir ==="
            helm dependency build "$chart_dir"
            helm lint $chart_dir
          done

          for chart in $(find infrastructure -name Chart.yaml -print); do
            chart_dir=$(dirname "$chart")
            echo "=== Helm lint $chart_dir ==="
            helm dependency build "$chart_dir"
            helm lint $chart_dir
          done